function [fitresult, gof] = createSurfFit(T, P, km, NAME, name)
%CREATEFIT(T,P,KM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: T
%      Y Input: P
%      Z Output: km
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-May-2023 16:08:41


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( T, P, km );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
%[fitresult, gof] = fit( [xData, yData], zData, ft );

plot_data = fit ([xData, yData], zData, ft);
contourplot = plot(plot_data);
set (contourplot, 'edgecolor', 'none')
x= linspace(min(xData),max(xData));
y= linspace(min(yData),max(yData));
[xx yy]=meshgrid(x,y);
zz = plot_data(xx,yy);
hold on 
%contourplotline = contour3(xx,yy,zz,[8.754 11.75],'LineWidth',2,'color','k');
plot3(T, P, km,'o')
hold off

grid off

xlabel( 'T' );
ylabel( 'P' );
zlabel( NAME);

set(gcf,'PaperOrientation','landscape'); print(figure(1),[name,'.pdf'],'-dpdf','-bestfit')

close all